### PR TITLE
Add sphinx dropdown styles

### LINKED ISSUE #163: Adapt custom style for sphinx dropdown
screenshot
Adapt the styles to have the borders and texts for sphinx dropdown.

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
Fix #163 
monospace
monospace_dark

### CODE REVIEW

**Review by jorgepiloto — APPROVED** [review]

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Comment by jorgepiloto** [comment]
Do you think it could be possible to use a monospace font for code-snippets, @Revathyvenugopal162?

**Comment by MaxJPRey** [comment]
> Do you think it could be possible to use a monospace font for code-snippets, @Revathyvenugopal162?

+1 for monospace font if possible.

**Comment by MaxJPRey** [comment]
@Revathyvenugopal162 whenever you can could you add a screenshot of the rendering of the code snippets with the new font.

**Comment by jorgepiloto** [comment]
Feel free to merge this when ready, @Revathyvenugopal162. It looks awesome 👍🏽

**Comment by jorgepiloto** [comment]
Wait, I just saw the following issue when using a `grid` object from sphinx-design:

Screenshot 2022-12-05 at 14-31-02 Licenses actions — PyAnsys Actions 2 0 dev0 documentation

This was found in https://github.com/pyansys/actions/pull/109.

**Comment by Revathyvenugopal162** [comment]
update_font
Updated the font size

**Pull request merged**
