### PR TITLE
fix: admonitions style

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
Associated with https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2201293227
# fix admonitions 

## light theme
Screenshot_29-7-2024_174256_

## dark theme
Screenshot_29-7-2024_174249_

### CODE REVIEW

**Comment by MaxJPRey** [comment]
Nice work @Revathyvenugopal162 .
Thanks for all the presentation related to it yesterday.

**Comment by jorgepiloto** [comment]
I bet it is tricky to get the admonition icon inline with the rest of the text for multi-line admonitions.

If we want to keep the icon next to the title of the admonition, then let's increase the margin between the icon and the left border of the admonition. Otherwise, icons for one-line admonitions and multi-line ones show a margin difference.

**Comment by Revathyvenugopal162** [comment]
> I bet it is tricky to get the admonition icon inline with the rest of the text for multi-line admonitions.
> 
> If we want to keep the icon next to the title of the admonition, then let's increase the margin between the icon and the left border of the admonition. Otherwise, icons for one-line admonitions and multi-line ones show a margin difference.

updated the margin and the screenshots

**Comment by jorgepiloto** [comment]
@Revathyvenugopal162, I can see both the admonition title and the content are left justified and aligned. However, the icon still shows a bigger margin than in the multi-line admonitions than in the multi-line admonitions than in the one-line ones.

**Comment by Revathyvenugopal162** [comment]
> @Revathyvenugopal162, I can see both the admonition title and the content are left justified and aligned. However, the icon still shows a bigger margin than in the multi-line admonitions than in the multi-line admonitions than in the one-line ones.

margin left for both the icons are same, but the right margin after the icons were different  , i just aligned it back, let me know if this works, otherwise i can revert with the small margin in between. 
image

**Review by jorgepiloto — APPROVED** [review]

**Pull request merged**
