### PR TITLE
fix: move the version switcher to left navigation bar

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
image

### CODE REVIEW

**Comment by RobPasMue** [comment]
Looks a bit odd, doesn't it? @ansys/pyansys-core

**Comment by RobPasMue** [comment]
Or maybe it's just me that I am already used to seeing it in the right top corner 😄

**Comment by SMoraisAnsys** [comment]
> Or maybe it's just me that I am already used to seeing it in the right top corner 😄

I'm also more familiar with seeing this at the top right corner (not only from pyansys documentations but other projects, e.g. https://matplotlib.org/stable/)

**Comment by germa89** [comment]
I agree with the other comments, right side looks better.

**Comment by Revathyvenugopal162** [comment]
In that case, i will close the PR and remove this from the meta issue.

**Comment by jorgepiloto** [comment]
Closing this as per the style guidelines suggested in #403

**Pull request closed without merging**
