### PR TITLE
Updata pydata-sphinx-theme.

### PR DESCRIPTION
**Pull request by germa89**
Update `pydata-sphinx-theme` to latest version. It should solve https://github.com/pyansys/pymapdl/pull/1167

I do not have write-access to this repo so I had to fork.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
CI is failing since `link_logo` is named now `logo`, see [pydata theme commit](https://github.com/pydata/pydata-sphinx-theme/commit/522a57f1cb8b2eca0e7c301ac7a8e72bbf73ddf2#diff-f0f04e8b873a8565b32c276f0dfcfbdb49b0f8b1c022d8cb59cd179872f542df). Could you @germa89 update this variable name in the `theme.conf` file?

**Comment by germa89** [comment]
@jorgepiloto  I did replace `link_logo` by `logo.link`.

**Review by jorgepiloto — APPROVED** [review]
Merging! Thanks @germa89 🚀

**Comment by jorgepiloto** [comment]
Need to investigate the PR labeling issues.

**Comment by germa89** [comment]
@jorgepiloto do you think you can cut a release in the coming days?

**Pull request merged**
