### PR TITLE
 Modify css for style changes

### LINKED ISSUE #117: Icons in annotations are too light
image

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
Fix #117 , #112 , #115  #114 #113 

- [x] Adding left side nav in similar way of right side nav-bar.
- [x] Add padding for the on on-this-page
- [x] Add link color to admonitions ( notes and info)
- [x] Modify the search bar text color
- [x] Modify the hover color 
- [x] add padding for images from text
- [x] Modify tab color for dark theme
left_panel
tabs
admonitions
padding
image

### CODE REVIEW

**Review by chadqueen — APPROVED** [review]

**Comment by MaxJPRey** [comment]
Thanks @Revathyvenugopal162 for addressing all the issues.

**Review by MaxJPRey — APPROVED** [review]

**Review by PipKat — APPROVED** [review]
Great work, Revathy!

**Review by jorgepiloto — APPROVED** [review]
Awesome! Thanks @Revathyvenugopal162 🚀

**Review by RobPasMue — APPROVED** [review]
LGTM! Thanks @Revathyvenugopal162

**Comment by RobPasMue** [comment]
Since all reviewers approved, I am merging this PR. Thank you all for reviewing and @Revathyvenugopal162 for the implementation!

**Pull request merged**
