### PR TITLE
fix: rename the extension name with no conflict

### LINKED ISSUE #274: Handler error in latest version
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When running the docs I'm getting this error:

```output
writing output... [ 87%] mapdl_commands/solution/_autosummary/ansys.mapdl.core.Mapdl.bfv .. mapdl_commands/solution/_autosummary/ansys.mapdl.core.Mapdl.mfelem
Sphinx parallel build error:
sphinx.errors.ExtensionError: Handler <function update_and_remove_templates at 0x7f55445a41f0> for event 'html-page-context' threw an exception (exception: 'ansys' is not in list)
make: *** [Makefile:21: html] Error 2
```
https://github.com/ansys/pymapdl/actions/runs/5870157592/job/15917918928?pr=2248#step:15:231

### 📝 Steps to reproduce

It happens in PyMAPDL CICD.

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

N/A

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
fix #274

### CODE REVIEW

**Comment by germa89** [comment]
I don't see how the changes proposed can aliviate #274 ... Can you explain a bit please?

**Comment by Revathyvenugopal162** [comment]
> I don't see how the changes proposed can alleviate #274 ... Can you explain a bit please?

i think the function 'fix_edit_link_button' is defined in ansys-sphinx theme and in pymapdl, made the jinja to add the function in html context, and shadowing  fix_edit_link_button function, leading to unexpected behavior of looking for an extension named ansys.

**Comment by Revathyvenugopal162** [comment]
I tried it locally and it is fixing my error for pymapdl!

**Comment by RobPasMue** [comment]
Oh... so it's because PyMAPDL has it's own function? In that case... we might want to change PyMAPDL rather than the Sphinx theme... right?

**Comment by Revathyvenugopal162** [comment]
> Oh... so it's because PyMAPDL has it's own function? In that case... we might want to change PyMAPDL rather than the Sphinx theme... right?

Yes, but i think we both got that name from pyvista, if we are adding this as another extension or add theme in public themes, it should not conflict another library, so i changed it here.!
But changing for the moment in pymapdl will also solve the issue.

**Comment by RobPasMue** [comment]
> Yes, but i think we both got that name from pyvista, if we are adding this as another extension or add theme in public themes, it should not conflict another library, so i changed it here.! But changing for the moment in pymapdl will also solve the issue.

Okay, let's accept the change then =)

**Review by RobPasMue — APPROVED** [review]

**Review by germa89 — APPROVED** [review]
With the recent explanations, I see the point for this PR and I approve it.

Looking forward to see this change in the next release. Thank a lot @Revathyvenugopal162 !! 😄

**Comment by germa89** [comment]
Also, how did you discover what was the reason? It seems to me the error was a bit obscure. Very good job!

**Comment by Revathyvenugopal162** [comment]
> By the way, I guess your fix for the "edit button" should also work with PyMAPDL I guess? So maybe we can remove that bit from PyMAPDL.

i believe, we can remove some code and the extension with these changes.

**Review by MaxJPRey — APPROVED** [review]
Thanks for the explaination @Revathyvenugopal162 .

**Comment by germa89** [comment]
> > By the way, I guess your fix for the "edit button" should also work with PyMAPDL I guess? So maybe we can remove that bit from PyMAPDL.
> 
> i believe, we can remove some code and the extension with these changes.

I will.. eventually... one day.. find the time for this. 🥲

**Comment by RobPasMue** [comment]
Can we merge this BTW?

**Comment by germa89** [comment]
We will need a patch release for this.

**Comment by RobPasMue** [comment]
Yep, @Revathyvenugopal162 - please plan on it

**Comment by Revathyvenugopal162** [comment]
Sure, i will do this Morning.

**Pull request merged**
