### PR TITLE
feat: add API templates

### PR DESCRIPTION
**Pull request by jorgepiloto**
This pull-request introduces a collection of templates to be reused by our libraries.

- [ ] Link every object into a single page. Not possible for the moment, see https://github.com/readthedocs/sphinx-autoapi/issues/226

- [x] Dynamically generated summary table made of tabs that dynamically splits between "packages", "modules", "interfaces", "classes", "enums", "constants", and "attributes"

- [x] Compact and optimize previous code using macros

- [x] Agree on a common set of globals to be used in the "index.rst" page of the template: project name, description...

### CODE REVIEW

**Comment by RobPasMue** [comment]
Hey guys! What's the status here? =)

**Review by RobPasMue — APPROVED** [review]
LGTM! Best way to test it is to see it life

**Comment by RobPasMue** [comment]
Can we get this merged and do a release asap? 0.11.0

**Comment by jorgepiloto** [comment]
Let's go with these changes. We will perform all the corresponding patch releases if we face any issues.

**Pull request merged**
