### PR TITLE
add light theme config to css

### LINKED ISSUE #74: Dark and light mode coming from  pydata-sphinx-theme 0.9.0
We should try and block the dark/light theme duality since it has caused our docs to adopt different styles and colors don't match now. See below:
image
image

We should try and block this new feature so that it is only shown in our format... or adapt the logos so that the color is adapted at least... But I'd definitely block the dark/light mode (at least for now)

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
Fix #74 
Screenshot (19)
Screenshot (20)

### CODE REVIEW

**Comment by RobPasMue** [comment]
Light theme works fine, but would there be a way to set the same "black" color for the logo and theme in dark mode?

**Comment by akaszynski** [comment]
> Light theme works fine, but would there be a way to set the same "black" color for the logo and theme in dark mode?

I think this should be added before merging this PR.

**Comment by germa89** [comment]
I wonder if it is better edit the CSS or the logo image.....

**Comment by Revathyvenugopal162** [comment]
We can change the color. I will update it now. For dark theme giving another logo is also possible.

**Comment by RobPasMue** [comment]
> 

Don't worry about editing the logo. In fact, the logo should stick to the official Ansys colours, Thus, I do agree with @germa89, its better editing the CSS files for the dark theme format. Thanks @Revathyvenugopal162

**Review by germa89 — APPROVED** [review]
Without checking the color values, it looks good to me. Looking forward to see the output online.

**Comment by RobPasMue** [comment]
image


Looks awesome @Revathyvenugopal162 ! Thanks for solving the problem

**Review by RobPasMue — APPROVED** [review]

**Comment by germa89** [comment]
I like the output a lot! The dark theme is much colorful though. But I like it that way. Good job @Revathyvenugopal162 !

**Comment by germa89** [comment]
I like the output a lot! The dark theme is much colorful though. But I like it that way. Good job @Revathyvenugopal162 !

**Pull request merged**
