### PR TITLE
fix: reformat the table styles

### LINKED ISSUE #403: Ansys Sphinx Theme - Design updates
**Sphinx design** : https://sphinxdocs.ansys.com/version/dev/examples/sphinx-design.html#

The following components could be enhanced to create a more streamlined user experience. 
- Cards (including card carousel)
- Buttons 
- Links
- Side navigation
- Selector 
- Dropdown 
- Table
- etc.

Please feel free to let me know if you have any concerns or if anything needs to be specified. Cheers!
FYI @Revathyvenugopal162 @jorgepiloto @RobPasMue

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
partially fixes #403

## normal table
normal state |  hover state | active state
:-------------------------:|:-------------------------:|:-------------------------:
n-tab  |  image | image |

## data table
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
d-table |  image  | image |

## long table -centered
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
l-table | image | image |

## Table centered
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
tab-c | image | image |

## Data frame - sphinx gallery
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
data-table-gall | image | image |

## Dataframe -nbsphinx
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
databa-nb | image |image |

### CODE REVIEW

**Review by RobPasMue — COMMENTED** [review]
They look good to me! I don't like the fact that when hovering or selecting the font style and size changes, but I don't know if you can control that

**Comment by Revathyvenugopal162** [comment]
For our normal table, the size remains unchanged. For data frames, it is adjusted. However, as mentioned in [this comment](https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179524578), there was a suggestion to change the size. I have now standardized the size accordingly. We can discuss and finalize the exact size , and i am pushing the  style adjustments.

**Comment by jorgepiloto** [comment]
I still can see the dataframe changing in size with the latest changes. Serve the docs with `cd doc/_build/html && python -m http.server`:

http://localhost:8000/examples/nbsphinx/jupyter-notebook.html#Render-a-data-frame

**Comment by Revathyvenugopal162** [comment]
> I still can see the dataframe changing in size with the latest changes. Serve the docs with `cd doc/_build/html && python -m http.server`:
> 
> http://localhost:8000/examples/nbsphinx/jupyter-notebook.html#Render-a-data-frame

ah, sorry, i didnt change the size, i changed the font family, [changed the hovering size.](https://github.com/ansys/ansys-sphinx-theme/pull/408/commits/cf5134ae591284741e43db67bc311d77b7446cec)

**Comment by Revathyvenugopal162** [comment]
updated the screenshot.

**Review by RobPasMue — APPROVED** [review]
Love it! Much better from my POV. Thanks @Revathyvenugopal162!

**Comment by jorgepiloto** [comment]
Ah! Agreed. Everything working fine, now 👍🏼

**Review by jorgepiloto — APPROVED** [review]
Awesome! Thanks, @Revathyvenugopal162.

**Pull request merged**
