### PR TITLE
fix: use ansys-sphinx-theme variables in CSS files

### PR DESCRIPTION
**Pull request by Abhinav-gh**
## Linked Issue

This PR addresses #531.

## Description

In this PR, I have replaced various hardcoded values across 3 CSS files with corresponding variables defined in the [ansys-sphinx-theme variables.css file](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css).  I have also tested it by running on my local device and have found there are no discrepancies.

**Note:** I have not made any modifications to the [ansys-sphinx-theme variables.css file](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css). file itself because the issue (#531) did not explicitly state to update that file. However, I have identified some additional hardcoded values that could potentially be moved to [ansys-sphinx-theme variables.css file](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css). for further improvement.

## Questions

Should I also update the [ansys-sphinx-theme variables.css file](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css).. to introduce new variables and replace more hardcoded values? Your feedback on this would be greatly appreciated.

## Review Request

Could you kindly review these changes and let me know if further adjustments are needed? I am happy to incorporate any additional changes or suggestions you might have.

## CLA Agreement
I agree with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

### CODE REVIEW

**Comment by RobPasMue** [comment]
HI @Revathyvenugopal162 - if you could replace further hardcoded variables as part of this PR I think it'd be great =)

**Review by RobPasMue — COMMENTED** [review]
As for the rest - LGTM

**Comment by Revathyvenugopal162** [comment]
> HI @Revathyvenugopal162 - if you could replace further hardcoded variables as part of this PR I think it'd be great =)

sure i can fix those

**Comment by RobPasMue** [comment]
Thank you for your contribution @Abhinav-gh! This is really appreciated =) Sorry, I deleted my previous comments because I thought the PR had be open by one of our colleagues. @Revathyvenugopal162 since you are the expert in this package, please review the PR at your earliest convenience.

**Comment by Revathyvenugopal162** [comment]
@Abhinav-gh Thank you for your contribution! I appreciate your findings on the hardcoded values. My suggestion is to add these properties to the variables.css file if they are background color, box shadow, drop shadow, font color, font-size or font family. Properties that stay the same between dark and light themes, such as font weight, can remain hardcoded. Font sizes, font family, and color variables should be defined in the variables.css file. 

If you find any such variables, feel free to add them using the naming convention with the --ast prefix. For example: `--ast-sphinx-design-tab-color`.

I hope this is clear. Feel free to reach out if you need any further clarification

**Comment by SMoraisAnsys** [comment]
@Abhinav-gh Thanks for this contribution. On top of your changes, can you update the [CONTIBUTORS.md](https://github.com/ansys/ansys-sphinx-theme/blob/main/CONTRIBUTORS.md) file to add your name as an individual contributor ? Also, can you state that you agree with the [CLA](https://developer.ansys.com/form/cla-acceptance) ?

**Comment by Abhinav-gh** [comment]
@SMoraisAnsys Sure. I will do that.

**Comment by jorgepiloto** [comment]
Hi @Abhinav-gh, as soon as you add yourself to the list of CONTRIBUTORS and accept the CLA, we can merge this. Your contribution solves two issues! Thanks! 🚀

**Comment by Abhinav-gh** [comment]
Hey @jorgepiloto ! I have added my name to the CONTRIBUTORS file and have already accepted the Contributor License Agreement (CLA). Thank you @Revathyvenugopal162  @RobPasMue @SMoraisAnsys for giving me this wonderful opportunity to contribute!

**Review by jorgepiloto — APPROVED** [review]

**Review by RobPasMue — APPROVED** [review]

**Comment by RobPasMue** [comment]
Let's merge even if failing - outside collaborators do not have access to secrets when PRs come from their forks

**Pull request merged**
