### PR TITLE
fix: section ids with search

### LINKED ISSUE #579: Bug located in ansys/doc-build@v8
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Our CI fails when upgrading the sphinx theme to 1.2.0 with the following error:

> Extension error (ansys_sphinx_theme.search.fuse_search):
> Handler <function create_search_index at 0x7f82c7d3a4d0> for event 'build-finished' threw an exception (exception: list index out of range)
> make: *** [Makefile:19: html] Error 2

### 📝 Steps to reproduce

https://github.com/ansys/grantami-bomanalytics/actions/runs/11619612949/job/32359611095?pr=640

Build the documentation for grantami-bomanalytics with Ansys sphinx theme 1.2.0

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

n/a

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

Installing dependencies from lock file

Package operations: 118 installs, 1 update, 0 removals

  - Installing attrs (24.2.0)
  - Installing rpds-py (0.20.0)
  - Installing referencing (0.35.1)
  - Installing six (1.16.0)
  - Installing jsonschema-specifications (2024.10.1)
  - Installing platformdirs (4.3.6)
  - Installing python-dateutil (2.9.0.post0)
  - Installing traitlets (5.14.3)
  - Installing types-python-dateutil (2.9.0.20241003)
  - Installing arrow (1.3.0)
  - Installing fastjsonschema (2.20.0)
  - Installing jsonschema (4.23.0)
  - Installing jupyter-core (5.7.2)
  - Installing pycparser (2.22)
  - Installing tornado (6.4.1)
  - Installing pyzmq (26.2.0)
  - Installing cffi (1.17.1)
  - Installing fqdn (1.5.1)
  - Installing idna (3.10)
  - Installing isoduration (20.11.0)
  - Installing jsonpointer (3.0.0)
  - Installing jupyter-client (8.6.3)
  - Installing markupsafe (3.0.2)
  - Installing nbformat (5.10.4)
  - Installing ptyprocess (0.7.0)
  - Installing rfc3339-validator (0.1.4)
  - Installing rfc3986-validator (0.1.1)
  - Installing soupsieve (2.6)
  - Installing uri-template (1.3.0)
  - Installing webcolors (24.8.0)
  - Installing webencodings (0.5.1)
  - Installing argon2-cffi-bindings (21.2.0)
  - Installing asttokens (2.4.1)
  - Installing beautifulsoup4 (4.12.3)
  - Installing bleach (6.1.0)
  - Installing certifi (2024.8.30)
  - Installing charset-normalizer (3.4.0)
  - Installing cryptography (43.0.3)
  - Installing defusedxml (0.7.1)
  - Installing exceptiongroup (1.2.2)
  - Installing executing (2.1.0)
  - Installing jinja2 (3.1.4)
  - Installing jupyterlab-pygments (0.3.0)
  - Installing mistune (3.0.2)
  - Installing nbclient (0.10.0)
  - Installing packaging (24.1)
  - Installing pandocfilters (1.5.1)
  - Installing parso (0.8.4)
  - Installing pure-eval (0.2.3)
  - Installing pygments (2.18.0)
  - Installing python-json-logger (2.0.7)
  - Installing pyyaml (6.0.2)
  - Installing sniffio (1.3.1)
  - Installing terminado (0.18.1)
  - Installing tinycss2 (1.4.0)
  - Installing typing-extensions (4.12.2)
  - Installing urllib3 (2.2.3)
  - Installing wcwidth (0.2.13)
  - Installing anyio (4.6.2.post1)
  - Installing argon2-cffi (23.1.0)
  - Installing decorator (5.1.1)
  - Installing h11 (0.14.0)
  - Installing jedi (0.19.1)
  - Installing jupyter-events (0.10.0)
  - Installing jupyter-server-terminals (0.5.3)
  - Installing matplotlib-inline (0.1.7)
  - Installing nbconvert (7.16.4)
  - Installing overrides (7.7.0)
  - Installing pexpect (4.9.0)
  - Installing prometheus-client (0.21.0)
  - Installing prompt-toolkit (3.0.48)
  - Installing pyspnego (0.11.1)
  - Installing requests (2.32.3)
  - Installing send2trash (1.8.3)
  - Installing stack-data (0.6.3)
  - Installing websocket-client (1.8.0)
  - Installing babel (2.16.0)
  - Installing comm (0.2.2)
  - Installing debugpy (1.8.7)
  - Installing httpcore (1.0.6)
  - Installing iniconfig (2.0.0)
  - Installing ipython (8.29.0)
  - Installing json5 (0.9.25)
  - Installing jupyter-server (2.14.2)
  - Installing nest-asyncio (1.6.0)
  - Installing pluggy (1.5.0)
  - Installing psutil (6.1.0)
  - Installing pyparsing (3.2.0)
  - Installing requests-ntlm (1.3.0)
  - Installing tomli (2.0.2)
  - Installing ansys-openapi-common (2.2.0)
  - Installing async-lru (2.0.4)
  - Installing coverage (7.6.4)
  - Installing elementpath (4.5.0)
  - Installing httpx (0.27.2)
  - Installing ipykernel (6.29.5)
  - Installing jupyter-lsp (2.2.5)
  - Installing jupyterlab-server (2.27.3)
  - Installing jupyterlab-widgets (3.0.13)
  - Installing mypy-extensions (1.0.0)
  - Installing notebook-shim (0.2.4)
  - Installing numpy (2.1.2)
  - Installing pytest (8.3.3)
  - Installing pytz (2024.2)
  - Updating setuptools (65.5.0 -> 75.2.0)
  - Installing tenacity (9.0.0)
  - Installing tzdata (2024.2)
  - Installing widgetsnbextension (4.0.13)
  - Installing ansys-grantami-bomanalytics-openapi (3.1.0rc1)
  - Installing ipywidgets (8.1.5)
  - Installing jupyterlab (4.3.0)
  - Installing lxml (5.3.0)
  - Installing mypy (1.13.0)
  - Installing pandas (2.2.3)
  - Installing plotly (5.24.1)
  - Installing pytest-cov (6.0.0)
  - Installing requests-mock (1.12.1)
  - Installing tabulate (0.9.0)
  - Installing xmlschema (3.4.2)

Installing the current project: ansys-grantami-bomanalytics (2.2.0dev0)
Run source .venv/bin/activate
Installing dependencies from lock file

Package operations: 47 installs, 0 updates, 0 removals

  - Installing natsort (8.4.0)
  - Installing alabaster (0.7.16)
  - Installing docutils (0.21.2)
  - Installing domdf-python-tools (3.9.0)
  - Installing imagesize (1.4.1)
  - Installing mdurl (0.1.2)
  - Installing more-itertools (10.5.0)
  - Installing snowballstemmer (2.2.0)
  - Installing sphinxcontrib-applehelp (2.0.0)
  - Installing sphinxcontrib-devhelp (2.0.0)
  - Installing sphinxcontrib-htmlhelp (2.1.0)
  - Installing sphinxcontrib-jsmath (1.0.1)
  - Installing sphinxcontrib-qthelp (2.0.0)
  - Installing sphinxcontrib-serializinghtml (2.0.0)
  - Installing accessible-pygments (0.0.5)
  - Installing apeye-core (1.1.5)
  - Installing cssutils (2.11.1)
  - Installing filelock (3.16.1)
  - Installing markdown-it-py (3.0.0)
  - Installing msgpack (1.1.0)
  - Installing pillow (11.0.0)
  - Installing ruamel-yaml-clib (0.2.12)
  - Installing sphinx (8.1.3)
  - Installing zipp (3.20.2)
  - Installing apeye (1.4.1)
  - Installing autodocsumm (0.2.14)
  - Installing cachecontrol (0.14.0)
  - Installing dict2css (0.3.0.post1)
  - Installing html5lib (1.1)
  - Installing importlib-metadata (8.5.0)
  - Installing mdit-py-plugins (0.4.2)
  - Installing pdf2image (1.17.0)
  - Installing pydata-sphinx-theme (0.15.4)
  - Installing ruamel-yaml (0.18.6)
  - Installing sphinx-autodoc-typehints (2.3.0)
  - Installing sphinx-jinja2-compat (0.3.0)
  - Installing sphinx-prompt (1.9.0)
  - Installing sphinx-tabs (3.4.5)
  - Installing ansys-sphinx-theme (1.2.0)
  - Installing enum-tools (0.12.0)
  - Installing jupytext (1.16.4)
  - Installing nbsphinx (0.9.5)
  - Installing numpydoc (1.8.0)
  - Installing sphinx-design (0.6.1)
  - Installing sphinx-notfound-page (1.0.4)
  - Installing sphinx-copybutton (0.5.2)
  - Installing sphinx-toolbox (3.8.1)

(CI run so cannot run pip freeze)

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
fix #579

### CODE REVIEW

**Comment by Revathyvenugopal162** [comment]
testing with https://github.com/ansys/grantami-bomanalytics/pull/644

**Review by MaxJPRey — APPROVED** [review]

**Comment by jorgepiloto** [comment]
Checking this in https://github.com/ansys/pydpf-core/pull/1846

**Review by jorgepiloto — APPROVED** [review]
Working for PyDPF. @da1910, could you confirm this branch is also working for your project?

**Comment by jorgepiloto** [comment]
@da1910 Confirmed that this is working for their projects. Let's merge it and perform a patch release, @Revathyvenugopal162.

**Comment by Revathyvenugopal162** [comment]
> @da1910 Confirmed that this is working for their projects. Let's merge it and perform a patch release, @Revathyvenugopal162.

sure, thanks Jorge, doing the patch

**Pull request merged**
