### PR TITLE
fix: add changelog action in ci-cd

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
add changelog actions in ci-cd, continuation of #370

### CODE REVIEW

**Review by RobPasMue — APPROVED** [review]
You'll need to give admin access to @pyansys-ci-bot for this to work :)

**Review by RobPasMue — APPROVED** [review]
You'll need to give admin access to @pyansys-ci-bot for this to work :)

**Comment by RobPasMue** [comment]
Just did it for you @Revathyvenugopal162

**Comment by Revathyvenugopal162** [comment]
> Just did it for you @Revathyvenugopal162

Thank you so much @RobPasMue

**Pull request merged**
